//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> select()
 * f1 -> selectList()
 * f2 -> from()
 * f3 -> identifier()
 * f4 -> [ where() booleanValueExpression() ]
 * f5 -> [ groupby() identifier() ]
 * f6 -> [ orderby() commonValueExpression() [ asc() | desc() ] ]
 * f7 -> ";"
 */
public class querySpecification implements Node {
   public select f0;
   public selectList f1;
   public from f2;
   public identifier f3;
   public NodeOptional f4;
   public NodeOptional f5;
   public NodeOptional f6;
   public NodeToken f7;

   public querySpecification(select n0, selectList n1, from n2, identifier n3, NodeOptional n4, NodeOptional n5, NodeOptional n6, NodeToken n7) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
   }

   public querySpecification(select n0, selectList n1, from n2, identifier n3, NodeOptional n4, NodeOptional n5, NodeOptional n6) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = new NodeToken(";");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

