//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors must implement this interface.
 */

public interface GJVisitor<R,A> {

   //
   // GJ Auto class visitors
   //

   public R visit(NodeList n, A argu);
   public R visit(NodeListOptional n, A argu);
   public R visit(NodeOptional n, A argu);
   public R visit(NodeSequence n, A argu);
   public R visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> queryList()
    * f1 -> <EOF>
    */
   public R visit(Prog n, A argu);

   /**
    * f0 -> querySpecification()
    * f1 -> ( querySpecification() )*
    */
   public R visit(queryList n, A argu);

   /**
    * f0 -> select()
    * f1 -> selectList()
    * f2 -> from()
    * f3 -> identifier()
    * f4 -> [ where() booleanValueExpression() ]
    * f5 -> [ groupby() identifier() ]
    * f6 -> [ orderby() commonValueExpression() [ asc() | desc() ] ]
    * f7 -> ";"
    */
   public R visit(querySpecification n, A argu);

   /**
    * f0 -> <SELECT>
    */
   public R visit(select n, A argu);

   /**
    * f0 -> asterisk()
    *       | derivedColumn() ( "," derivedColumn() )*
    */
   public R visit(selectList n, A argu);

   /**
    * f0 -> <asterisk>
    */
   public R visit(asterisk n, A argu);

   /**
    * f0 -> commonValueExpression()
    * f1 -> [ [ as() ] identifier() ]
    */
   public R visit(derivedColumn n, A argu);

   /**
    * f0 -> "(" commonValueExpression() ")"
    *       | nonparenthesizedValueExpressionPrimary()
    */
   public R visit(commonValueExpression n, A argu);

   /**
    * f0 -> identifier()
    *       | <setfunctiontype> "(" commonValueExpression() ")"
    *       | <number>
    */
   public R visit(nonparenthesizedValueExpressionPrimary n, A argu);

   /**
    * f0 -> <AS>
    */
   public R visit(as n, A argu);

   /**
    * f0 -> <FROM>
    */
   public R visit(from n, A argu);

   /**
    * f0 -> <identifier>
    */
   public R visit(identifier n, A argu);

   /**
    * f0 -> <WHERE>
    */
   public R visit(where n, A argu);

   /**
    * f0 -> booleanTerm()
    * f1 -> booleanValueExpressionPrime()
    */
   public R visit(booleanValueExpression n, A argu);

   /**
    * f0 -> ( or() booleanTerm() booleanValueExpressionPrime() )?
    */
   public R visit(booleanValueExpressionPrime n, A argu);

   /**
    * f0 -> <OR>
    */
   public R visit(or n, A argu);

   /**
    * f0 -> booleanFactor()
    * f1 -> booleanTermPrime()
    */
   public R visit(booleanTerm n, A argu);

   /**
    * f0 -> ( and() booleanFactor() booleanTermPrime() )?
    */
   public R visit(booleanTermPrime n, A argu);

   /**
    * f0 -> <AND>
    */
   public R visit(and n, A argu);

   /**
    * f0 -> [ not() ]
    * f1 -> boleanPredicand()
    * f2 -> [ <compop> boleanPredicand() ]
    */
   public R visit(booleanFactor n, A argu);

   /**
    * f0 -> <NOT>
    */
   public R visit(not n, A argu);

   /**
    * f0 -> "(" booleanValueExpression() ")"
    *       | nonparenthesizedValueExpressionPrimary()
    */
   public R visit(boleanPredicand n, A argu);

   /**
    * f0 -> <GROUPBY>
    */
   public R visit(groupby n, A argu);

   /**
    * f0 -> <ORDERBY>
    */
   public R visit(orderby n, A argu);

   /**
    * f0 -> <ASC>
    */
   public R visit(asc n, A argu);

   /**
    * f0 -> <DESC>
    */
   public R visit(desc n, A argu);

}
