//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> queryList()
    * f1 -> <EOF>
    */
   public void visit(Prog n);

   /**
    * f0 -> querySpecification()
    * f1 -> ( querySpecification() )*
    */
   public void visit(queryList n);

   /**
    * f0 -> select()
    * f1 -> selectList()
    * f2 -> from()
    * f3 -> identifier()
    * f4 -> [ where() booleanValueExpression() ]
    * f5 -> [ groupby() identifier() ]
    * f6 -> [ orderby() commonValueExpression() [ asc() | desc() ] ]
    * f7 -> ";"
    */
   public void visit(querySpecification n);

   /**
    * f0 -> <SELECT>
    */
   public void visit(select n);

   /**
    * f0 -> asterisk()
    *       | derivedColumn() ( "," derivedColumn() )*
    */
   public void visit(selectList n);

   /**
    * f0 -> <asterisk>
    */
   public void visit(asterisk n);

   /**
    * f0 -> commonValueExpression()
    * f1 -> [ [ as() ] identifier() ]
    */
   public void visit(derivedColumn n);

   /**
    * f0 -> "(" commonValueExpression() ")"
    *       | nonparenthesizedValueExpressionPrimary()
    */
   public void visit(commonValueExpression n);

   /**
    * f0 -> identifier()
    *       | <setfunctiontype> "(" commonValueExpression() ")"
    *       | <number>
    */
   public void visit(nonparenthesizedValueExpressionPrimary n);

   /**
    * f0 -> <AS>
    */
   public void visit(as n);

   /**
    * f0 -> <FROM>
    */
   public void visit(from n);

   /**
    * f0 -> <identifier>
    */
   public void visit(identifier n);

   /**
    * f0 -> <WHERE>
    */
   public void visit(where n);

   /**
    * f0 -> booleanTerm()
    * f1 -> booleanValueExpressionPrime()
    */
   public void visit(booleanValueExpression n);

   /**
    * f0 -> ( or() booleanTerm() booleanValueExpressionPrime() )?
    */
   public void visit(booleanValueExpressionPrime n);

   /**
    * f0 -> <OR>
    */
   public void visit(or n);

   /**
    * f0 -> booleanFactor()
    * f1 -> booleanTermPrime()
    */
   public void visit(booleanTerm n);

   /**
    * f0 -> ( and() booleanFactor() booleanTermPrime() )?
    */
   public void visit(booleanTermPrime n);

   /**
    * f0 -> <AND>
    */
   public void visit(and n);

   /**
    * f0 -> [ not() ]
    * f1 -> boleanPredicand()
    * f2 -> [ <compop> boleanPredicand() ]
    */
   public void visit(booleanFactor n);

   /**
    * f0 -> <NOT>
    */
   public void visit(not n);

   /**
    * f0 -> "(" booleanValueExpression() ")"
    *       | nonparenthesizedValueExpressionPrimary()
    */
   public void visit(boleanPredicand n);

   /**
    * f0 -> <GROUPBY>
    */
   public void visit(groupby n);

   /**
    * f0 -> <ORDERBY>
    */
   public void visit(orderby n);

   /**
    * f0 -> <ASC>
    */
   public void visit(asc n);

   /**
    * f0 -> <DESC>
    */
   public void visit(desc n);

}

