/* Generated By:JavaCC: Do not edit this line. SQLParser.java */
import syntaxtree.*;
import java.util.Vector;


class SQLParser implements SQLParserConstants {

  static final public Prog Prog() throws ParseException {
   queryList n0;
   NodeToken n1;
   Token n2;
    n0 = queryList();
    n2 = jj_consume_token(0);
      n2.beginColumn++; n2.endColumn++;
      n1 = JTBToolkit.makeNodeToken(n2);
     {if (true) return new Prog(n0,n1);}
    throw new Error("Missing return statement in function");
  }

  static final public queryList queryList() throws ParseException {
   querySpecification n0;
   NodeListOptional n1 = new NodeListOptional();
   querySpecification n2;
    n0 = querySpecification();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SELECT:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      n2 = querySpecification();
        n1.addNode(n2);
    }
     n1.nodes.trimToSize();
     {if (true) return new queryList(n0,n1);}
    throw new Error("Missing return statement in function");
  }

  static final public querySpecification querySpecification() throws ParseException {
   select n0;
   from n1;
   NodeOptional n2 = new NodeOptional();
   where n3;
   NodeOptional n4 = new NodeOptional();
   groupby n5;
   NodeOptional n6 = new NodeOptional();
   orderby n7;
   NodeToken n8;
   Token n9;
    n0 = select();
    n1 = from();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case WHERE:
      n3 = where();
        n2.addNode(n3);
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case GROUPBY:
      n5 = groupby();
        n4.addNode(n5);
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ORDERBY:
      n7 = orderby();
        n6.addNode(n7);
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    n9 = jj_consume_token(semicolon);
            n8 = JTBToolkit.makeNodeToken(n9);
     {if (true) return new querySpecification(n0,n1,n2,n4,n6,n8);}
    throw new Error("Missing return statement in function");
  }

  static final public select select() throws ParseException {
   NodeToken n0;
   Token n1;
   NodeChoice n2;
   NodeToken n3;
   Token n4;
   NodeSequence n5;
   commonValueExpression n6;
   NodeListOptional n7 = new NodeListOptional();
   NodeSequence n8;
   NodeToken n9;
   Token n10;
   commonValueExpression n11;
    n1 = jj_consume_token(SELECT);
                 n0 = JTBToolkit.makeNodeToken(n1);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case asterisk:
      n4 = jj_consume_token(asterisk);
                  n3 = JTBToolkit.makeNodeToken(n4);
           n2 = new NodeChoice(n3, 0);
      break;
    case identifier:
    case leftparen:
    case setfunctiontype:
    case number:
           n5 = new NodeSequence(2);
      n6 = commonValueExpression();
           n5.addNode(n6);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case comma:
          ;
          break;
        default:
          jj_la1[4] = jj_gen;
          break label_2;
        }
              n8 = new NodeSequence(2);
        n10 = jj_consume_token(comma);
                      n9 = JTBToolkit.makeNodeToken(n10);
              n8.addNode(n9);
        n11 = commonValueExpression();
              n8.addNode(n11);
              n7.addNode(n8);
      }
           n7.nodes.trimToSize();
           n5.addNode(n7);
           n2 = new NodeChoice(n5, 1);
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
     {if (true) return new select(n0,n2);}
    throw new Error("Missing return statement in function");
  }

  static final public from from() throws ParseException {
   NodeToken n0;
   Token n1;
   identifier n2;
    n1 = jj_consume_token(FROM);
               n0 = JTBToolkit.makeNodeToken(n1);
    n2 = identifier();
     {if (true) return new from(n0,n2);}
    throw new Error("Missing return statement in function");
  }

  static final public where where() throws ParseException {
   NodeToken n0;
   Token n1;
   identifier n2;
   NodeToken n3;
   Token n4;
   NodeChoice n5;
   identifier n6;
   NodeToken n7;
   Token n8;
    n1 = jj_consume_token(WHERE);
                n0 = JTBToolkit.makeNodeToken(n1);
    n2 = identifier();
    n4 = jj_consume_token(compop);
                 n3 = JTBToolkit.makeNodeToken(n4);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case identifier:
      n6 = identifier();
           n5 = new NodeChoice(n6, 0);
      break;
    case number:
      n8 = jj_consume_token(number);
                       n7 = JTBToolkit.makeNodeToken(n8);
           n5 = new NodeChoice(n7, 1);
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
     {if (true) return new where(n0,n2,n3,n5);}
    throw new Error("Missing return statement in function");
  }

  static final public groupby groupby() throws ParseException {
   NodeToken n0;
   Token n1;
   identifier n2;
    n1 = jj_consume_token(GROUPBY);
                  n0 = JTBToolkit.makeNodeToken(n1);
    n2 = identifier();
     {if (true) return new groupby(n0,n2);}
    throw new Error("Missing return statement in function");
  }

  static final public orderby orderby() throws ParseException {
   NodeToken n0;
   Token n1;
   identifier n2;
   NodeOptional n3 = new NodeOptional();
   NodeChoice n4;
   NodeToken n5;
   Token n6;
   NodeToken n7;
   Token n8;
    n1 = jj_consume_token(ORDERBY);
                  n0 = JTBToolkit.makeNodeToken(n1);
    n2 = identifier();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASC:
    case DESC:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ASC:
        n6 = jj_consume_token(ASC);
                    n5 = JTBToolkit.makeNodeToken(n6);
           n4 = new NodeChoice(n5, 0);
        break;
      case DESC:
        n8 = jj_consume_token(DESC);
                     n7 = JTBToolkit.makeNodeToken(n8);
           n4 = new NodeChoice(n7, 1);
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
        n3.addNode(n4);
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
     {if (true) return new orderby(n0,n2,n3);}
    throw new Error("Missing return statement in function");
  }

  static final public commonValueExpression commonValueExpression() throws ParseException {
   NodeChoice n0;
   NodeSequence n1;
   NodeToken n2;
   Token n3;
   commonValueExpression n4;
   NodeToken n5;
   Token n6;
   nonparenthesizedValueExpressionPrimary n7;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case leftparen:
        n1 = new NodeSequence(3);
      n3 = jj_consume_token(leftparen);
               n2 = JTBToolkit.makeNodeToken(n3);
        n1.addNode(n2);
      n4 = commonValueExpression();
        n1.addNode(n4);
      n6 = jj_consume_token(rightparen);
               n5 = JTBToolkit.makeNodeToken(n6);
        n1.addNode(n5);
        n0 = new NodeChoice(n1, 0);
      break;
    case identifier:
    case setfunctiontype:
    case number:
      n7 = nonparenthesizedValueExpressionPrimary();
        n0 = new NodeChoice(n7, 1);
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
     {if (true) return new commonValueExpression(n0);}
    throw new Error("Missing return statement in function");
  }

  static final public nonparenthesizedValueExpressionPrimary nonparenthesizedValueExpressionPrimary() throws ParseException {
   NodeChoice n0;
   identifier n1;
   setFunctionType n2;
   NodeToken n3;
   Token n4;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case identifier:
      n1 = identifier();
        n0 = new NodeChoice(n1, 0);
      break;
    case setfunctiontype:
      n2 = setFunctionType();
        n0 = new NodeChoice(n2, 1);
      break;
    case number:
      n4 = jj_consume_token(number);
                    n3 = JTBToolkit.makeNodeToken(n4);
        n0 = new NodeChoice(n3, 2);
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
     {if (true) return new nonparenthesizedValueExpressionPrimary(n0);}
    throw new Error("Missing return statement in function");
  }

  static final public identifier identifier() throws ParseException {
   NodeToken n0;
   Token n1;
    n1 = jj_consume_token(identifier);
                     n0 = JTBToolkit.makeNodeToken(n1);
     {if (true) return new identifier(n0);}
    throw new Error("Missing return statement in function");
  }

  static final public setFunctionType setFunctionType() throws ParseException {
   NodeToken n0;
   Token n1;
   NodeToken n2;
   Token n3;
   NodeToken n4;
   Token n5;
   NodeToken n6;
   Token n7;
    n1 = jj_consume_token(setfunctiontype);
                          n0 = JTBToolkit.makeNodeToken(n1);
    n3 = jj_consume_token(leftparen);
            n2 = JTBToolkit.makeNodeToken(n3);
    n5 = jj_consume_token(identifier);
                     n4 = JTBToolkit.makeNodeToken(n5);
    n7 = jj_consume_token(rightparen);
            n6 = JTBToolkit.makeNodeToken(n7);
     {if (true) return new setFunctionType(n0,n2,n4,n6);}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public SQLParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[11];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x20,0x80,0x100,0x200,0x400,0x8b800,0x80800,0x6000000,0x6000000,0x8a800,0x88800,};
   }

  /** Constructor with InputStream. */
  public SQLParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SQLParser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SQLParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 11; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 11; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public SQLParser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SQLParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 11; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 11; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public SQLParser(SQLParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 11; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(SQLParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 11; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[27];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 11; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 27; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}

class JTBToolkit {
   static NodeToken makeNodeToken(Token t) {
      return new NodeToken(t.image.intern(), t.kind, t.beginLine, t.beginColumn, t.endLine, t.endColumn);
   }
}
