/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int FROM = 6;
  /** RegularExpression Id. */
  int WHERE = 7;
  /** RegularExpression Id. */
  int GROUPBY = 8;
  /** RegularExpression Id. */
  int ORDERBY = 9;
  /** RegularExpression Id. */
  int comma = 10;
  /** RegularExpression Id. */
  int identifier = 11;
  /** RegularExpression Id. */
  int asterisk = 12;
  /** RegularExpression Id. */
  int leftparen = 13;
  /** RegularExpression Id. */
  int rightparen = 14;
  /** RegularExpression Id. */
  int setfunctiontype = 15;
  /** RegularExpression Id. */
  int digit = 16;
  /** RegularExpression Id. */
  int integer = 17;
  /** RegularExpression Id. */
  int real = 18;
  /** RegularExpression Id. */
  int number = 19;
  /** RegularExpression Id. */
  int semicolon = 20;
  /** RegularExpression Id. */
  int equalsoperator = 21;
  /** RegularExpression Id. */
  int lessthanoperator = 22;
  /** RegularExpression Id. */
  int greaterthanoperator = 23;
  /** RegularExpression Id. */
  int compop = 24;
  /** RegularExpression Id. */
  int ASC = 25;
  /** RegularExpression Id. */
  int DESC = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"GROUP BY\"",
    "\"ORDER BY\"",
    "\",\"",
    "<identifier>",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "<setfunctiontype>",
    "<digit>",
    "<integer>",
    "<real>",
    "<number>",
    "\";\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "<compop>",
    "\"ASC\"",
    "\"DESC\"",
  };

}
