/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int FROM = 6;
  /** RegularExpression Id. */
  int WHERE = 7;
  /** RegularExpression Id. */
  int GROUPBY = 8;
  /** RegularExpression Id. */
  int ORDERBY = 9;
  /** RegularExpression Id. */
  int comma = 10;
  /** RegularExpression Id. */
  int identifier = 11;
  /** RegularExpression Id. */
  int asterisk = 12;
  /** RegularExpression Id. */
  int AS = 13;
  /** RegularExpression Id. */
  int leftparen = 14;
  /** RegularExpression Id. */
  int rightparen = 15;
  /** RegularExpression Id. */
  int setfunctiontype = 16;
  /** RegularExpression Id. */
  int digit = 17;
  /** RegularExpression Id. */
  int integer = 18;
  /** RegularExpression Id. */
  int real = 19;
  /** RegularExpression Id. */
  int number = 20;
  /** RegularExpression Id. */
  int OR = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int truthValue = 23;
  /** RegularExpression Id. */
  int semicolon = 24;
  /** RegularExpression Id. */
  int IS = 25;
  /** RegularExpression Id. */
  int NOT = 26;
  /** RegularExpression Id. */
  int equalsoperator = 27;
  /** RegularExpression Id. */
  int lessthanoperator = 28;
  /** RegularExpression Id. */
  int greaterthanoperator = 29;
  /** RegularExpression Id. */
  int compop = 30;
  /** RegularExpression Id. */
  int ASC = 31;
  /** RegularExpression Id. */
  int DESC = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"GROUP BY\"",
    "\"ORDER BY\"",
    "\",\"",
    "<identifier>",
    "\"*\"",
    "\"AS\"",
    "\"(\"",
    "\")\"",
    "<setfunctiontype>",
    "<digit>",
    "<integer>",
    "<real>",
    "<number>",
    "\"OR\"",
    "\"AND\"",
    "<truthValue>",
    "\";\"",
    "\"IS\"",
    "\"NOT\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "<compop>",
    "\"ASC\"",
    "\"DESC\"",
  };

}
